# Generated by Django 4.1.7 on 2023-04-21 06:14

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('image', versatileimagefield.fields.VersatileImageField(upload_to='service')),
                ('sub_head', models.CharField(max_length=50)),
                ('detail', models.TextField()),
                ('title2', models.CharField(blank=True, max_length=100, null=True)),
                ('image2', versatileimagefield.fields.VersatileImageField(upload_to='service')),
                ('sub_head2', models.CharField(max_length=50)),
                ('detail2', models.TextField()),
            ],
        ),
    ]
