# Generated by Django 4.1.7 on 2023-04-25 09:04

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_gallery_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='detail2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='image2',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='service'),
        ),
        migrations.AddField(
            model_name='package',
            name='sub_head',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='sub_head2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='title2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
